-- Sample IQ Test Questions
INSERT INTO questions (test_id, question_text, question_type, options, correct_answer, order_number) VALUES
-- IQ Test Questions (test_id = 1) - 35 Questions
(1, 'What comes next in the sequence: 2, 4, 8, 16, ?', 'multiple_choice', '["16", "24", "32", "64"]', '32', 1),
(1, 'If all Bloops are Razzies and all Razzies are Lazzies, then all Bloops are definitely Lazzies?', 'multiple_choice', '["True", "False", "Cannot be determined", "None of the above"]', 'True', 2),
(1, 'Which number should replace the question mark: 3, 6, 11, 18, 27, ?', 'multiple_choice', '["36", "38", "40", "42"]', '38', 3),
(1, 'Book is to Reading as Fork is to:', 'multiple_choice', '["Drawing", "Writing", "Stirring", "Eating"]', 'Eating', 4),
(1, 'Which of the following is least like the others: Dog, Mouse, Lion, Snake, Elephant', 'multiple_choice', '["Dog", "Mouse", "Lion", "Snake"]', 'Snake', 5),
(1, 'If you rearrange the letters "CIFAIPC" you would have the name of a:', 'multiple_choice', '["City", "Animal", "Ocean", "River"]', 'Ocean', 6),
(1, 'What number is one half of one quarter of one tenth of 800?', 'multiple_choice', '["4", "8", "10", "40"]', '10', 7),
(1, 'Mary is twice as old as Ann was when Mary was as old as Ann is now. If Mary is 24, how old is Ann?', 'multiple_choice', '["12", "16", "18", "20"]', '18', 8),
(1, 'Which word does not belong: Apple, Grape, Banana, Cherry, Potato', 'multiple_choice', '["Apple", "Grape", "Banana", "Potato"]', 'Potato', 9),
(1, 'Complete the analogy: Day is to Night as Summer is to:', 'multiple_choice', '["Spring", "Winter", "Fall", "Rain"]', 'Winter', 10),
(1, 'What is the next number in the sequence: 1, 1, 2, 3, 5, 8, ?', 'multiple_choice', '["11", "13", "15", "21"]', '13', 11),
(1, 'If 5 cats can catch 5 mice in 5 minutes, how many cats are needed to catch 100 mice in 100 minutes?', 'multiple_choice', '["5", "20", "25", "100"]', '5', 12),
(1, 'Which number is the odd one out: 2, 5, 7, 11, 13, 15', 'multiple_choice', '["2", "5", "13", "15"]', '15', 13),
(1, 'Water is to Ice as Milk is to:', 'multiple_choice', '["Cream", "Cheese", "Butter", "Yogurt"]', 'Cheese', 14),
(1, 'What comes next: A, C, F, J, O, ?', 'multiple_choice', '["S", "T", "U", "V"]', 'U', 15),
(1, 'If A=1, B=2, C=3... what does CAT equal?', 'multiple_choice', '["24", "27", "30", "33"]', '24', 16),
(1, 'Which shape completes the pattern: Circle, Square, Triangle, Circle, Square, ?', 'multiple_choice', '["Circle", "Square", "Triangle", "Pentagon"]', 'Triangle', 17),
(1, 'What is the missing number: 2, 6, 12, 20, 30, ?', 'multiple_choice', '["38", "40", "42", "44"]', '42', 18),
(1, 'Pen is to Writer as Brush is to:', 'multiple_choice', '["Painter", "Teacher", "Doctor", "Engineer"]', 'Painter', 19),
(1, 'Which word can be made from the letters: DEROR', 'multiple_choice', '["ORDER", "OLDER", "DORER", "RODEO"]', 'ORDER', 20),
(1, 'What is the next letter: J, F, M, A, M, ?', 'multiple_choice', '["J", "A", "S", "N"]', 'J', 21),
(1, 'If you have 3 apples and you take away 2, how many do you have?', 'multiple_choice', '["1", "2", "3", "5"]', '2', 22),
(1, 'Which number should replace X: 7, 14, 28, X, 112', 'multiple_choice', '["42", "49", "56", "70"]', '56', 23),
(1, 'Hot is to Cold as Light is to:', 'multiple_choice', '["Bright", "Dark", "Heavy", "Soft"]', 'Dark', 24),
(1, 'What comes next: 100, 96, 92, 88, ?', 'multiple_choice', '["80", "82", "84", "86"]', '84', 25),
(1, 'Which word is the opposite of EXPAND?', 'multiple_choice', '["Contract", "Inflate", "Grow", "Increase"]', 'Contract', 26),
(1, 'If 2 + 3 = 10, 3 + 4 = 14, what is 4 + 5?', 'multiple_choice', '["18", "20", "22", "24"]', '20', 27),
(1, 'Which number is different: 16, 25, 36, 48, 64', 'multiple_choice', '["16", "25", "48", "64"]', '48', 28),
(1, 'Clock is to Time as Thermometer is to:', 'multiple_choice', '["Heat", "Temperature", "Weather", "Degree"]', 'Temperature', 29),
(1, 'What is the next number: 3, 9, 27, 81, ?', 'multiple_choice', '["162", "243", "324", "405"]', '243', 30),
(1, 'Which word does not belong: Mercury, Venus, Earth, Jupiter, Saturn', 'multiple_choice', '["Mercury", "Venus", "Earth", "Saturn"]', 'Earth', 31),
(1, 'If it takes 5 machines 5 minutes to make 5 widgets, how long would it take 100 machines to make 100 widgets?', 'multiple_choice', '["5 minutes", "20 minutes", "100 minutes", "500 minutes"]', '5 minutes', 32),
(1, 'Which number completes the pattern: 1, 4, 9, 16, 25, ?', 'multiple_choice', '["30", "35", "36", "49"]', '36', 33),
(1, 'Shoe is to Foot as Hat is to:', 'multiple_choice', '["Hand", "Head", "Leg", "Body"]', 'Head', 34),
(1, 'What is the missing letter: A, D, G, J, ?', 'multiple_choice', '["K", "L", "M", "N"]', 'M', 35);

-- Career Assessment Questions (test_id = 2) - 35 Questions
INSERT INTO questions (test_id, question_text, question_type, options, correct_answer, order_number) VALUES
(2, 'I prefer working with:', 'multiple_choice', '["People", "Data and numbers", "Creative projects", "Technical systems"]', '', 1),
(2, 'In my free time, I enjoy:', 'multiple_choice', '["Reading and learning", "Building or fixing things", "Socializing", "Creating art or music"]', '', 2),
(2, 'When faced with a problem, I:', 'multiple_choice', '["Analyze it logically", "Seek advice from others", "Think of creative solutions", "Look for practical fixes"]', '', 3),
(2, 'My ideal work environment is:', 'multiple_choice', '["Structured and organized", "Dynamic and social", "Flexible and independent", "Innovative and creative"]', '', 4),
(2, 'I am most interested in:', 'multiple_choice', '["Science and technology", "Arts and humanities", "Business and management", "Healthcare and helping others"]', '', 5),
(2, 'I excel at:', 'multiple_choice', '["Problem-solving", "Communication", "Planning and organizing", "Innovation and design"]', '', 6),
(2, 'My learning style is:', 'multiple_choice', '["Visual (seeing)", "Auditory (hearing)", "Kinesthetic (doing)", "Reading/Writing"]', '', 7),
(2, 'I prefer tasks that are:', 'multiple_choice', '["Detailed and precise", "Collaborative", "Independent", "Creative and open-ended"]', '', 8),
(2, 'When working in a team, I usually:', 'multiple_choice', '["Lead and organize", "Support and help", "Generate ideas", "Execute and implement"]', '', 9),
(2, 'I am motivated by:', 'multiple_choice', '["Achievement and success", "Helping others", "Personal growth", "Financial rewards"]', '', 10),
(2, 'My biggest strength is:', 'multiple_choice', '["Attention to detail", "Empathy and understanding", "Creative thinking", "Technical skills"]', '', 11),
(2, 'I would rather:', 'multiple_choice', '["Work alone on complex tasks", "Lead a team project", "Collaborate with others", "Explore new ideas"]', '', 12),
(2, 'When making decisions, I rely on:', 'multiple_choice', '["Facts and data", "Gut feeling", "Others opinions", "Past experiences"]', '', 13),
(2, 'I am naturally good at:', 'multiple_choice', '["Math and logic", "Writing and speaking", "Art and design", "Understanding people"]', '', 14),
(2, 'My ideal career would involve:', 'multiple_choice', '["Research and analysis", "Teaching or counseling", "Design and creativity", "Management and leadership"]', '', 15),
(2, 'I prefer to spend my time:', 'multiple_choice', '["Indoors at a desk", "Outdoors and active", "Meeting with people", "In a lab or workshop"]', '', 16),
(2, 'When learning something new, I:', 'multiple_choice', '["Read the manual first", "Jump right in and experiment", "Ask someone to show me", "Watch tutorial videos"]', '', 17),
(2, 'I am most productive when:', 'multiple_choice', '["Working on a schedule", "Under pressure", "In a creative flow", "Collaborating with others"]', '', 18),
(2, 'My dream job would be:', 'multiple_choice', '["Scientist or engineer", "Artist or designer", "Doctor or therapist", "CEO or entrepreneur"]', '', 19),
(2, 'I enjoy activities that are:', 'multiple_choice', '["Mentally challenging", "Physically active", "Socially engaging", "Creatively stimulating"]', '', 20),
(2, 'When stressed, I prefer to:', 'multiple_choice', '["Analyze the situation", "Talk to someone", "Take a break and relax", "Work harder to solve it"]', '', 21),
(2, 'I am interested in:', 'multiple_choice', '["How things work", "Human behavior", "Visual aesthetics", "Business strategies"]', '', 22),
(2, 'My natural role in a group is:', 'multiple_choice', '["The planner", "The mediator", "The innovator", "The executor"]', '', 23),
(2, 'I would enjoy a career that involves:', 'multiple_choice', '["Data analysis", "Public speaking", "Graphic design", "Laboratory work"]', '', 24),
(2, 'My approach to projects is:', 'multiple_choice', '["Systematic and methodical", "Flexible and adaptive", "Collaborative and inclusive", "Innovative and experimental"]', '', 25),
(2, 'I am drawn to subjects like:', 'multiple_choice', '["Mathematics and physics", "Literature and philosophy", "Music and art", "Biology and medicine"]', '', 26),
(2, 'In a perfect world, I would:', 'multiple_choice', '["Solve complex problems", "Help people in need", "Create beautiful things", "Build successful businesses"]', '', 27),
(2, 'I prefer work that is:', 'multiple_choice', '["Predictable and stable", "Varied and changing", "People-oriented", "Results-driven"]', '', 28),
(2, 'My favorite school subjects were:', 'multiple_choice', '["Science and math", "English and history", "Art and music", "Physical education"]', '', 29),
(2, 'When starting a project, I first:', 'multiple_choice', '["Research thoroughly", "Brainstorm ideas", "Discuss with team", "Make a detailed plan"]', '', 30),
(2, 'I value:', 'multiple_choice', '["Accuracy and precision", "Creativity and originality", "Relationships and harmony", "Achievement and recognition"]', '', 31),
(2, 'My communication style is:', 'multiple_choice', '["Direct and factual", "Warm and empathetic", "Inspiring and motivational", "Structured and clear"]', '', 32),
(2, 'I am energized by:', 'multiple_choice', '["Solving puzzles", "Helping others", "Creating art", "Leading projects"]', '', 33),
(2, 'My ideal workplace offers:', 'multiple_choice', '["Cutting-edge technology", "Collaborative culture", "Creative freedom", "Clear advancement paths"]', '', 34),
(2, 'When I retire, I want to be known for:', 'multiple_choice', '["My innovations", "Impact on people lives", "My creative works", "My business success"]', '', 35);
